import {
  BellRing,
  BookOpenText,
  Calculator,
  CandlestickChart,
  FlaskConical,
  GraduationCap,
  History,
  LayoutDashboard,
  Network,
  Newspaper,
  Settings,
  ShieldCheck,
  Sparkles,
  Telescope,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  CandlestickChart,
  Network,
  Wallet,
  History,
  Telescope,
  Sparkles,
  Newspaper,
  Users,
  FlaskConical,
  BellRing,
  Calculator,
  BookOpenText,
  GraduationCap,
  Settings,
  ShieldCheck,
};
